elastic-operator: add new chart
iits-consulting/charts pull request #127
Opened 2024-08-08 13:12 UTC by d-schl-iits

using the (new) propsed way to deploy eck-stack

2024-08-09 10:50 UTC, d-schl-iits commented
- [ ] check middlewares of ingresses (admin-forward-auth vs oidc-forward-auth)
- [ ] adjust elastalert values.yaml and add an example on how to connect the two. Example config:

```yaml
elastalert2:
  elasticsearch:
    # needs to be in the same namespaces as elastic stack if used like this
    host: elastic-operator-es-http
    useSsl: "True"
    caCerts: "/certs/tls.crt"
    certsVolumes:
      - name: elasticsearch-certs
        secret:
          defaultMode: 420
          secretName: elastic-operator-es-http-certs-public
    certsVolumeMounts:
      - name: elasticsearch-certs
        mountPath: /certs
        readOnly: true
```

2024-09-02 10:06 UTC, krankkkk requested changes
Wie ist das mit der Migration elastic-stack -> operator?
Kann man einfach 1:1 die Volumes weiter benutzen, oder ist das effektiv ein backup&restore? Kannst du da bitte eine Readme für den nächsten mit rein packen.

+ Deine offenen TODO's solltest du noch abschließen.

2024-09-02 10:06 UTC, krankkkk commented on charts/elastic-operator/templates/kyverno/operator.yaml
> +            - {{ $.Release.Name }}-?
Ist das wirklich `-?`

2024-09-02 10:06 UTC, krankkkk commented on charts/elastic-operator/templates/kyverno/kibana.yaml
> +        - check-seccomp-strict
Sicher das Kibana überhaupt PolicyExclusions braucht?

2024-09-02 10:06 UTC, krankkkk commented on charts/elastic-operator/values.yaml
> +  repoName: "elastic-backups"
Hier scheint was nicht zu klappen, Playground Backups failen weil die policy auf s3_backups zeigt, es das repo aber nicht mehr gibt

2024-09-02 10:06 UTC, krankkkk commented on charts/elastic-operator/values.yaml
> +                order: 1
Geht das auch mit unserem Standart OIDC?

2024-09-17 13:52 UTC, d-schl-iits commented on charts/elastic-operator/values.yaml
> +                order: 1
Wenn du meinst, dass der Gatekeeper der vor Kibana läuft damit funktioniert, dann ja
Wenn du "echtes" OIDC zwischen Keycloak und Kibana / Elasticsearch meinst, dann nein (weil nicht von der freien Lizenz abgedeckt)

2024-09-17 13:55 UTC, d-schl-iits commented on charts/elastic-operator/values.yaml
> +  repoName: "elastic-backups"
Auf dem Playground funktionieren die Backups aktuell, vermutlich hat das jemand gefixt?

Die Azure-Variante ist jedenfalls getestet auf dem Projekt und läuft zuverlässig.

2024-09-17 13:58 UTC, d-schl-iits commented on charts/elastic-operator/templates/kyverno/kibana.yaml
> +        - check-seccomp-strict
Ich bin einzeln die Policy-Reports von kyverno durchgegangen und habe für alles was dort aufgetaucht ist eine Exception geschrieben (analog zu deinen templates im "elasticsearch"-Chart) (basierend auf unseren vanilla kyverno-Policies aus dem "kyverno"-Chart).

Bei mir waren aber auch definitiv Kibana-Meldungen dabei die eigentlich im alten Chart auch vorhanden sein müssten. Aber ich überprüfe es nochmal...

2024-09-17 14:00 UTC, d-schl-iits commented on charts/elastic-operator/templates/kyverno/operator.yaml
> +            - {{ $.Release.Name }}-?
Das geht davon aus, dass wir maximal eine einstellige Anzahl von Operator-Pods haben, weil es namentliche Überschneidungen mit anderen Pods gibt, die sonst hier mit dem allgemeinen Wildcard gematched werden würden.

2024-12-16 15:12 UTC, d-schl-iits commented on charts/elastic-operator/templates/kyverno/kibana.yaml
> +        - check-seccomp-strict
Ich habe bei Kibana jetzt explizite securityContexts auf allen Containern gesetzt, dadurch kann die Exception weg :+1:

2025-01-17 13:31 UTC, d-schl-iits commented
The index-pattern API of kibana changed. This needs to be adjusted before merging

2025-01-30 16:08 UTC, merged